#pragma once

#include "QuoteApi_API.h"

#define qfPreClose	 				FidMean_PreClosingPrice			//昨收盘价
#define qfPreSettle	 				FidMean_PreSettlePrice			//昨结算价
#define qfPrePosition	 			FidMean_PrePositionQty			//昨持仓量
#define qfOpen						FidMean_OpeningPrice			//开盘价
#define qfLast		 				FidMean_LastPrice				//最新价
#define qfHigh		 				FidMean_HighPrice				//最高价
#define qfLow		 				FidMean_LowPrice				//最低价
#define qfHisHigh	 				FidMean_HisHighPrice			//历史最高价
#define qfHisLow		 			FidMean_HisLowPrice				//历史最低价
#define qfLimitUp	 				FidMean_LimitUpPrice			//涨停价
#define qfLimitDown	 				FidMean_LimitDownPrice			//跌停价
#define qfTotalQty		 			FidMean_TotalQty				//当日总成交量
#define qfPosition		 			FidMean_PositionQty				//持仓量
#define qfAverage	 				FidMean_AveragePrice			//均价                    
#define qfClose	 					FidMean_ClosingPrice			//收盘价            
#define qfSettle		 			FidMean_SettlePrice				//结算价            
#define qfLastQty			 		FidMean_LastQty					//最新成交量
#define qfBidPrice1		 			FidMean_BidPrice_1				//买价1   
#define qfBidPrice2		 			FidMean_BidPrice_2				//买价2                                     
#define qfBidPrice3		 			FidMean_BidPrice_3				//买价3                         
#define qfBidPrice4		 			FidMean_BidPrice_4				//买价4                           
#define qfBidPrice5		 			FidMean_BidPrice_5				//买价5                         
#define qfBidPrice6		 			FidMean_BidPrice_6				//买价6                       
#define qfBidPrice7		 			FidMean_BidPrice_7				//买价7                    
#define qfBidPrice8		 			FidMean_BidPrice_8				//买价8                              
#define qfBidPrice9		 			FidMean_BidPrice_9				//买价9                         
#define qfBidPrice10		 		FidMean_BidPrice_10				//买价10                       
#define qfBidPrice11		 		FidMean_BidPrice_11				//买价11                          
#define qfBidPrice12		 		FidMean_BidPrice_12				//买价12                        
#define qfBidPrice13		 		FidMean_BidPrice_13				//买价13
#define qfBidPrice14		 		FidMean_BidPrice_14				//买价14
#define qfBidPrice15		 		FidMean_BidPrice_15				//买价15      
#define qfBidPrice16		 		FidMean_BidPrice_16				//买价16                          
#define qfBidPrice17		 		FidMean_BidPrice_17				//买价17                 
#define qfBidPrice18		 		FidMean_BidPrice_18				//买价18                
#define qfBidPrice19		 		FidMean_BidPrice_19				//买价19                
#define qfBidPrice20		 		FidMean_BidPrice_20				//买价20
#define qfBidQty1		 			FidMean_BidQty_1				//买量1
#define qfBidQty2		 			FidMean_BidQty_2				//买量2
#define qfBidQty3		 			FidMean_BidQty_3				//买量3
#define qfBidQty4		 			FidMean_BidQty_4				//买量4
#define qfBidQty5		 			FidMean_BidQty_5				//买量5
#define qfBidQty6		 			FidMean_BidQty_6				//买量6
#define qfBidQty7		 			FidMean_BidQty_7				//买量7
#define qfBidQty8		 			FidMean_BidQty_8				//买量8
#define qfBidQty9		 			FidMean_BidQty_9				//买量9
#define qfBidQty10		 			FidMean_BidQty_10				//买量10
#define qfBidQty11		 			FidMean_BidQty_11				//买量11
#define qfBidQty12		 			FidMean_BidQty_12				//买量12
#define qfBidQty13		 			FidMean_BidQty_13				//买量13
#define qfBidQty14		 			FidMean_BidQty_14				//买量14
#define qfBidQty15		 			FidMean_BidQty_15				//买量15 
#define qfBidQty16		 			FidMean_BidQty_16				//买量16 
#define qfBidQty17		 			FidMean_BidQty_17				//买量17 
#define qfBidQty18		 			FidMean_BidQty_18				//买量18 
#define qfBidQty19		 			FidMean_BidQty_19				//买量19 
#define qfBidQty20		 			FidMean_BidQty_20				//买量20 
#define qfAskPrice1		 			FidMean_AskPrice_1				//卖价1        
#define qfAskPrice2		 			FidMean_AskPrice_2				//卖价2                       
#define qfAskPrice3		 			FidMean_AskPrice_3				//卖价3                          
#define qfAskPrice4		 			FidMean_AskPrice_4				//卖价4                 
#define qfAskPrice5		 			FidMean_AskPrice_5				//卖价5                 
#define qfAskPrice6		 			FidMean_AskPrice_6				//卖价6                        
#define qfAskPrice7		 			FidMean_AskPrice_7				//卖价7       
#define qfAskPrice8		 			FidMean_AskPrice_8				//卖价8                      
#define qfAskPrice9		 			FidMean_AskPrice_9				//卖价9                
#define qfAskPrice10		 		FidMean_AskPrice_10				//卖价10               
#define qfAskPrice11		 		FidMean_AskPrice_11				//卖价11    
#define qfAskPrice12		 		FidMean_AskPrice_12				//卖价12          
#define qfAskPrice13		 		FidMean_AskPrice_13				//卖价13                     
#define qfAskPrice14		 		FidMean_AskPrice_14				//卖价14           
#define qfAskPrice15		 		FidMean_AskPrice_15				//卖价15          
#define qfAskPrice16		 		FidMean_AskPrice_16				//卖价16                 
#define qfAskPrice17		 		FidMean_AskPrice_17				//卖价17        
#define qfAskPrice18		 		FidMean_AskPrice_18				//卖价18         
#define qfAskPrice19		 		FidMean_AskPrice_19				//卖价19                     
#define qfAskPrice20		 		FidMean_AskPrice_20				//卖价20    
#define qfAskQty1		 			FidMean_AskQty_1				//卖量1 
#define qfAskQty2		 			FidMean_AskQty_2				//卖量2 
#define qfAskQty3		 			FidMean_AskQty_3				//卖量3 
#define qfAskQty4		 			FidMean_AskQty_4				//卖量4 
#define qfAskQty5		 			FidMean_AskQty_5				//卖量5 
#define qfAskQty6		 			FidMean_AskQty_6				//卖量6 
#define qfAskQty7		 			FidMean_AskQty_7				//卖量7 
#define qfAskQty8		 			FidMean_AskQty_8				//卖量8 
#define qfAskQty9		 			FidMean_AskQty_9				//卖量9 
#define qfAskQty10		 			FidMean_AskQty_10				//卖量10 
#define qfAskQty11		 			FidMean_AskQty_11				//卖量11 
#define qfAskQty12		 			FidMean_AskQty_12				//卖量12 
#define qfAskQty13		 			FidMean_AskQty_13				//卖量13 
#define qfAskQty14		 			FidMean_AskQty_14				//卖量14 
#define qfAskQty15		 			FidMean_AskQty_15				//卖量15 
#define qfAskQty16		 			FidMean_AskQty_16				//卖量16 
#define qfAskQty17		 			FidMean_AskQty_17				//卖量17 
#define qfAskQty18		 			FidMean_AskQty_18				//卖量18 
#define qfAskQty19		 			FidMean_AskQty_19				//卖量19 
#define qfAskQty20		 			FidMean_AskQty_20				//卖量20    
#define qfImpliedBidPrice	 		FidMean_ImpliedBidPrice			//隐含买价        
#define qfImpliedBidQty	 			FidMean_ImpliedBidQty			//隐含买量       
#define qfImpliedAskPrice	 		FidMean_ImpliedAskPrice			//隐含卖价     
#define qfImpliedAskQty	 			FidMean_ImpliedAskQty			//隐含卖量 
#define qfPreDelta		 			FidMean_PreDelta				//昨虚实度 
#define qfCurrDelta		 			FidMean_CurrDelta				//今虚实度 
#define qfInside		 			FidMean_InsideQty				//内盘量 
#define qfOutside		 			FidMean_OutsideQty				//外盘量 
#define qfTotalBid		 			FidMean_TotalBidQty				//委买总量 
#define qfTotalAsk		 			FidMean_TotalAskQty				//委卖总量 
#define qfTotalTurnover	 			FidMean_TotalTurnover			//总成交额 
#define qfInvalid			 		FidMean_Invalid					//无效字段
#define qfTradeState		 		FidMean_TradeState				//合约交易状态
#define qfDateTime			 		FidMean_DateTime				//更新时间
#define qfMAX				 		FidMean_MAX						//最大号
